apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: certificates-discovery

images:
  - name: certificates-discovery
    newName: prosimcorp/certificates-discovery
    newTag: v0.1.0

commonLabels:
  app.kubernetes.io/name: certificates-discovery

resources:
  # Canonical resources
  - namespace.yaml
  - deployment.yaml
  - serviceAccount.yaml
  - role.yaml
  - roleBinding.yaml
