apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: certificates-discovery-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete