apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certificates-discovery-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certificates-discovery-role
subjects:
  - kind: ServiceAccount
    name: certificates-discovery-sa